# Portainer uses a from scratch container and copies the alpine certs over
FROM alpine:latest as builder
COPY root_ca.crt /root_ca.crt
RUN cat /root_ca.crt >> /etc/ssl/certs/ca-certificates.crt

FROM portainer/portainer-ce:latest
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
