services:
  step-ca:
    image: [URL]/smallstep/step-ca:latest
    container_name: step-ca
    restart: unless-stopped
    ports: 
      - [IP]:443:443
    volumes:
      - step:/home/step
      - /etc/hosts:/etc/hosts:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true
  watchtower:
    image: [URL]/containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - NO_COLOR=true
      - WATCHTOWER_POLL_INTERVAL=21600
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_TIMEOUT=200s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  portainer-agent:
    image: [URL]/portainer/agent:latest
    container_name: portainer-agent
    hostname: portainer-agent
    restart: unless-stopped
    environment:
      - AGENT_SECRET=${AGENT_SECRET}
    ports:
      - [IP]:9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  step:
    external: true
