version: "3.7"

services:
  ocis:
    image: owncloud/ocis:latest
    #networks:
    #  ocis-net:
    entrypoint:
      - /bin/sh
    # run ocis init to initialize a configuration file with random secrets
    # it will fail on subsequent runs, because the config file already exists
    # therefore we ignore the error and then start the ocis server
    command: ["-c", "ocis init || true; ocis server"]
    environment:
      # Keycloak IDP specific configuration
      PROXY_AUTOPROVISION_ACCOUNTS: "true"
      OCIS_OIDC_ISSUER: https://URL
      WEB_OIDC_CLIENT_ID: ID
      # general config
      OCIS_URL: https://URL
      OCIS_LOG_LEVEL: error # make oCIS less verbose
      OCIS_LOG_COLOR: "false"
      PROXY_TLS: "false" # do not use SSL between Traefik and oCIS
      # INSECURE: needed if oCIS / Traefik is using self generated certificates
      OCIS_INSECURE: "false"
    volumes:
      - ocis-data:/var/lib/ocis
    #labels:
      #
    ports:
      - 9200:9200
    logging:
      driver: "local"
    restart: always
  caddy:
    image: URL/caddy:latest
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:z
      - ./root_ca.crt:/root_ca.crt:z
      #- $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
    #networks:
    #  - caddy_net
    labels:
      - com.centurylinklabs.watchtower.enable=true
volumes:
  ocis-config:
    external: true
  ocis-data:
    external: true
  caddy_data:
  caddy_config:
